import Foundation

extension String {
    static let appName = "SportSync"
    static let continueText = "Continue"
    static let welcomeHeadline = "The ultimate app for sports addicts!"
    static let welcomeSubtitle = "Every game,every fan,one app"
    static let logInText = "Login"
    static let signUpText = "Signup"
    static let emailPlaceholder = "Email address / Phone Number"
    static let passwordPlaceholder = "Your password"
    static let forgotPassword = "Forgot Password?"
    static let firstNamePlaceholder = "First Name"
    static let lastNamePlaceholder = "Last Name"
    static let confirmPasswordPlaceholder = "Confirm Password"
    static let age = "Your age"
    static let gender = "Gender"
    static let signUpHeadline = "Enter your details"
    static let signUpProgressText = "Details Complete"
    static let fontJakarta = "PlusJakarta-Regular"
    static let signUpAlertMessage = "Invalid email password format, mismatched passwords, or missing details. Please try again."
    static let signUpAlertTitle = "Invalid Credentials!"
    
    static let logInAlertMessage = "Check your email or password. Please try again."
    static let logInAlertTitle = "Invalid Email or Password!"
    static let forgotPasswordTitle = "Forgot your password ?"
    static let forgotPasswordMessage = "We’ll sent you new password on your mail"
    static let resetPasswordString = "Reset Password"
    static let OTPTitle = "OTP Verification"
    static let OTPMessage = "We have sent OTP to"
    static let OTPButtonTitle = "Send OTP"
    static let resetOTPString = "Resend OTP in "
    static let signUpSuccessString = "Sign up successful"
    static let signUpSuccessMessage = "You will be redirected to the main page in a few moments"
    static let fontJakartaBold = "PlusJakartaSans-Bold"
    static let homeTabName = "Home"
    static let profileTabName = "Profile"
    static let myEventTabName = "My Events"
    static let feedsTabName = "Feeds"
    static let currentlocationString = "Current location"
    static let createPlanString = "Create Plan"
    static let eventViewMessage = "Looks like you don’t have any upcoming plans. You can start from here.."
    static let selectSportString = "Select Sport"
    static let createEventString = "Create your event"
    static let otherDetailString = "Other Details"
    static let eventNameString = "Event Name"
    static let sportsNameString = "Sports Name"
    static let eventDateString = "Event Date"
    static let eventTimeString = "Event Time"
    static let eventSearchString = "Select basket ball court..."
    static let editPlanString = "Edit Plan"
    static let sharePlanString = "Share Plan"
    static let popularCourtsString = "Popular Courts"
    static let searchPopularStadiumString = "Search Popular Courts ..."
    static let selectLocationString = "Find my current location"
    static let privacyPolicyString = "Privacy Policy "
    static let TermsConditionString = "Terms & Conditions "
    static let lastestUpdateString = "Latest Update, "
    static let introductionHeading = "1. Introduction"
    static let informationWeCollectString = "2. Information We Collect"
    static let introductionMessageString = "Welcome to Sports Sync!We are committed to protecting your privacy and ensuring you have a safe and personalized experience while using our app. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use Sports Sync, whether through our mobile application or any associated services. By using Sports Sync, you agree to the practices described in this policy.Our goal is to give you full transparency and control over your data. If you have any questions or concerns about this policy or our data practices, feel free to contact us."
    static let informationWeCollectMessageString = "We collect limited information to provide and improve your experience on Sports Sync:Account Information: Name, email, and profile photo (if provided).App Activity: Events you create or join, features you use, and your preferences.Device Information: Device type, operating system, and general location (if permission is granted).Third-Party Logins: Basic profile info (name and email) if you sign in with Apple or Google."
    static let termsConditionString = "Terms & Condition"

}
