import Foundation

extension String {
    static let appName = "SportSync"
    static let continueText = "Continue"
    static let welcomeHeadline = "The ultimate app for sports addicts!"
    static let welcomeSubtitle = "Every game,every fan,one app"
    static let logInText = "Login"
    static let signUpText = "Signup"
    static let emailPlaceholder = "Email address / Phone Number"
    static let passwordPlaceholder = "Your password"
    static let forgotPassword = "Forgot Password?"
    static let firstNamePlaceholder = "First Name"
    static let lastNamePlaceholder = "Last Name"
    static let confirmPasswordPlaceholder = "Confirm Password"
    static let age = "Your age"
    static let gender = "Gender"
    static let signUpHeadline = "Enter your details"
    static let signUpProgressText = "Details Complete"
    static let fontJakarta = "PlusJakarta-Regular"
    static let signUpAlertMessage = "Invalid email password format, mismatched passwords, or missing details. Please try again."
    static let signUpAlertTitle = "Invalid Credentials!"
    
    static let logInAlertMessage = "Check your email or password. Please try again."
    static let logInAlertTitle = "Invalid Email or Password!"
    static let forgotPasswordTitle = "Forgot your password ?"
    static let forgotPasswordMessage = "We’ll sent you new password on your mail"
    static let resetPasswordString = "Reset Password"
    static let OTPTitle = "OTP Verification"
    static let OTPMessage = "We have sent OTP to"
    static let OTPButtonTitle = "Send OTP"
    static let resetOTPString = "Resend OTP in "
    static let signUpSuccessString = "Sign up successful"
    static let signUpSuccessMessage = "You will be redirected to the main page in a few moments"
    static let fontJakartaBold = "PlusJakartaSans-Bold"
    static let homeTabName = "Home"
    static let profileTabName = "Profile"
    static let myEventTabName = "My Events"
    static let feedsTabName = "Feeds"
    static let currentlocationString = "Current location"
    static let createPlanString = "Create plan"
    static let eventViewMessage = "Looks like you don’t have any upcoming plans. You can start from here.."
    static let selectSportString = "Select Sport"
}
